classDiagram
direction RL
%%Jeremy Trejos Murillo / 4-0261-0848

%%usuario
%%Casillero
%%Paquete
%%Envio
%%Rastreo

class Usuario{
    +String email
    +String contrasena
    }

class Casillero{
    +String id_Casillero
    +String ubicacion
    +boolean estado_Disponible
}

class Paquete{
    +String id_Paquete
    +String descripcion
    +int peso
    }

class Envio{
    +String id_Envio
    +String Nombre_Remitente
    +String Nombre_Destinatario
    +Date fecha_Envio
    +Date fecha_Entrega
    +String estado_Envio
    }

class Rastreo{
  +String id_Rastreo
  +String actualizacion_Estado
}

Usuario "1" -- "0..*" Casillero : posee >
Casillero "1" -- "0..*" Paquete : contiene > 
Paquete "1" -- "1" Envio : asociado >
Envio "1" -- "0..*" Rastreo : tiene >
